language: java
jdk:
  - oraclejdk8
env:
    global:
    - AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION=us-east-1

sudo: false
install: true

script:
  - pwd
  - cd build/distributions/
  - ls -al
  - cd build/lib/
  - ls -al
  - cd ../..
  - pwd
  - ls -al

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - pip install awscli --upgrade --user


after_success:
  - pwd
  - ls -al
  - cp build/distributions/lambda-dpk-nmn.zip .
  - mkdir lambda_artifact
  - ls -al
  - cp lambda-dpk-nmn.zip lambda_artifact/
  - ls -al
  - pwd
  - cd lambda_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:

  - provider: s3
    local_dir: lambda_artifact
    bucket: $S3_BUCKET_LAMBDA
    region: us-east-1
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    on:
      all_branches: true

  - provider: script
    skip_cleanup: true
    script: bash lambda.sh
    on:
      all_branches: true